#!/usr/bin/env python3
"""
Generate custom PlatformIO build configuration for CrossPoint Reader.
Allows selective enabling/disabling of features to reduce firmware size.
"""

import argparse
import sys
from pathlib import Path
from typing import Dict, List


class Feature:
    """Represents a toggleable firmware feature."""

    def __init__(self, name: str, flag: str, size_kb: int, description: str):
        self.name = name
        self.flag = flag
        self.size_kb = size_kb
        self.description = description


# Define all toggleable features
FEATURES = {
    'extended_fonts': Feature(
        name='Extended Fonts',
        flag='ENABLE_EXTENDED_FONTS',
        size_kb=300,
        description='12/16/18pt fonts and OpenDyslexic support'
    ),
    'image_sleep': Feature(
        name='PNG/JPEG Sleep Images',
        flag='ENABLE_IMAGE_SLEEP',
        size_kb=140,
        description='PNG and JPEG sleep screen support (BMP always included)'
    ),
    'markdown': Feature(
        name='Markdown/Obsidian',
        flag='ENABLE_MARKDOWN',
        size_kb=560,
        description='Markdown and Obsidian vault reading support'
    ),
    'background_server': Feature(
        name='Background Server',
        flag='ENABLE_BACKGROUND_SERVER',
        size_kb=5,
        description='Background web server for file management'
    ),
}


# Define presets
PRESETS = {
    'minimal': {
        'description': 'All features disabled (~5.5MB, -1.1MB savings)',
        'features': {}  # All disabled
    },
    'standard': {
        'description': 'Extended fonts + Image sleep (~6.2MB, recommended)',
        'features': {
            'extended_fonts': True,
            'image_sleep': True,
            'markdown': False,
            'background_server': False,
        }
    },
    'full': {
        'description': 'All features enabled (~6.6MB, current baseline)',
        'features': {
            'extended_fonts': True,
            'image_sleep': True,
            'markdown': True,
            'background_server': True,
        }
    },
}


def calculate_size(enabled_features: Dict[str, bool]) -> float:
    """Calculate estimated firmware size in MB."""
    base_size_mb = 5.5  # Minimal build size

    for feature_key, enabled in enabled_features.items():
        if enabled:
            base_size_mb += FEATURES[feature_key].size_kb / 1024.0

    return base_size_mb


def generate_build_flags(enabled_features: Dict[str, bool]) -> List[str]:
    """Generate PlatformIO build flags for the given feature set."""
    flags = []

    for feature_key, feature in FEATURES.items():
        value = 1 if enabled_features.get(feature_key, False) else 0
        flags.append(f'-D{feature.flag}={value}')

    return flags


def generate_platformio_ini(enabled_features: Dict[str, bool], output_path: Path):
    """Generate platformio-custom.ini with custom build configuration."""

    build_flags = generate_build_flags(enabled_features)
    estimated_size = calculate_size(enabled_features)

    # Generate feature list for comment
    enabled_list = []
    disabled_list = []
    for feature_key in FEATURES.keys():
        feature = FEATURES[feature_key]
        enabled = enabled_features.get(feature_key, False)
        if enabled:
            enabled_list.append(f'{feature.name} ({feature.size_kb}K)')
        else:
            disabled_list.append(feature.name)

    enabled_comment = '\n'.join(f'#   - {name}' for name in enabled_list) if enabled_list else '#   (none)'
    disabled_comment = '\n'.join(f'#   - {name}' for name in disabled_list) if disabled_list else '#   (none)'

    content = f"""# Custom CrossPoint Reader Build Configuration
# Generated by generate_build_config.py
#
# Estimated firmware size: ~{estimated_size:.1f}MB
#
# Enabled features:
{enabled_comment}
#
# Disabled features:
{disabled_comment}

[env:custom]
extends = base
build_flags =
  ${{base.build_flags}}
  -DCROSSPOINT_VERSION="${{crosspoint.version}}-custom"
{chr(10).join(f'  {flag}' for flag in build_flags)}
"""

    output_path.write_text(content)
    print(f"Generated {output_path}")
    print(f"Estimated firmware size: ~{estimated_size:.1f}MB")
    print(f"\nEnabled features:")
    for name in enabled_list:
        print(f"  ✓ {name}")
    if disabled_list:
        print(f"\nDisabled features:")
        for name in disabled_list:
            print(f"  ✗ {name}")


def main():
    parser = argparse.ArgumentParser(
        description='Generate custom CrossPoint Reader build configuration',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  # Use a preset
  %(prog)s --preset minimal
  %(prog)s --preset standard
  %(prog)s --preset full

  # Enable specific features
  %(prog)s --enable extended_fonts --enable image_sleep

  # Disable specific features from full build
  %(prog)s --preset full --disable markdown

  # List available features
  %(prog)s --list-features
"""
    )

    parser.add_argument(
        '--preset',
        choices=['minimal', 'standard', 'full'],
        help='Use a predefined feature preset'
    )

    parser.add_argument(
        '--enable',
        action='append',
        choices=list(FEATURES.keys()),
        help='Enable a specific feature (can be used multiple times)'
    )

    parser.add_argument(
        '--disable',
        action='append',
        choices=list(FEATURES.keys()),
        help='Disable a specific feature (can be used multiple times)'
    )

    parser.add_argument(
        '--output',
        type=Path,
        default=Path('platformio-custom.ini'),
        help='Output file path (default: platformio-custom.ini)'
    )

    parser.add_argument(
        '--list-features',
        action='store_true',
        help='List all available features and exit'
    )

    args = parser.parse_args()

    # Handle --list-features
    if args.list_features:
        print("Available features:\n")
        for key, feature in FEATURES.items():
            print(f"  {key:20} - {feature.name}")
            print(f"  {'':20}   {feature.description}")
            print(f"  {'':20}   Size impact: ~{feature.size_kb}K")
            print()

        print("\nAvailable presets:\n")
        for preset_name, preset_info in PRESETS.items():
            print(f"  {preset_name:10} - {preset_info['description']}")

        return 0

    # Determine enabled features
    enabled_features = {}

    if args.preset:
        # Start with preset
        enabled_features = PRESETS[args.preset]['features'].copy()
        print(f"Using preset: {args.preset}")
        print(f"  {PRESETS[args.preset]['description']}")
    else:
        # Default: all features disabled
        for feature_key in FEATURES.keys():
            enabled_features[feature_key] = False

    # Apply --enable flags
    if args.enable:
        for feature_key in args.enable:
            enabled_features[feature_key] = True

    # Apply --disable flags
    if args.disable:
        for feature_key in args.disable:
            enabled_features[feature_key] = False

    # Generate configuration
    generate_platformio_ini(enabled_features, args.output)

    print(f"\nTo build: pio run -e custom")

    return 0


if __name__ == '__main__':
    sys.exit(main())
