#pragma once

// Central source of truth for compile-time feature toggles.
// Build flags (e.g. -DENABLE_MARKDOWN=0) override these defaults.

#ifdef ENABLE_BOOKERLY_FONTS
#define FEATURE_OVERRIDE_ENABLE_BOOKERLY_FONTS 1
#else
#define FEATURE_OVERRIDE_ENABLE_BOOKERLY_FONTS 0
#endif

#ifdef ENABLE_NOTOSANS_FONTS
#define FEATURE_OVERRIDE_ENABLE_NOTOSANS_FONTS 1
#else
#define FEATURE_OVERRIDE_ENABLE_NOTOSANS_FONTS 0
#endif

#ifdef ENABLE_OPENDYSLEXIC_FONTS
#define FEATURE_OVERRIDE_ENABLE_OPENDYSLEXIC_FONTS 1
#else
#define FEATURE_OVERRIDE_ENABLE_OPENDYSLEXIC_FONTS 0
#endif

#ifdef ENABLE_MARKDOWN
#define FEATURE_OVERRIDE_ENABLE_MARKDOWN 1
#else
#define FEATURE_OVERRIDE_ENABLE_MARKDOWN 0
#endif

#ifdef ENABLE_INTEGRATIONS
#define FEATURE_OVERRIDE_ENABLE_INTEGRATIONS 1
#else
#define FEATURE_OVERRIDE_ENABLE_INTEGRATIONS 0
#endif

#ifdef ENABLE_KOREADER_SYNC
#define FEATURE_OVERRIDE_ENABLE_KOREADER_SYNC 1
#else
#define FEATURE_OVERRIDE_ENABLE_KOREADER_SYNC 0
#endif

#ifdef ENABLE_CALIBRE_SYNC
#define FEATURE_OVERRIDE_ENABLE_CALIBRE_SYNC 1
#else
#define FEATURE_OVERRIDE_ENABLE_CALIBRE_SYNC 0
#endif

#ifdef ENABLE_EPUB_SUPPORT
#define FEATURE_OVERRIDE_ENABLE_EPUB_SUPPORT 1
#else
#define FEATURE_OVERRIDE_ENABLE_EPUB_SUPPORT 0
#endif

#ifdef ENABLE_HYPHENATION
#define FEATURE_OVERRIDE_ENABLE_HYPHENATION 1
#else
#define FEATURE_OVERRIDE_ENABLE_HYPHENATION 0
#endif

#ifdef ENABLE_BOOK_IMAGES
#define FEATURE_OVERRIDE_ENABLE_BOOK_IMAGES 1
#else
#define FEATURE_OVERRIDE_ENABLE_BOOK_IMAGES 0
#endif

#ifdef ENABLE_WEB_POKEDEX_PLUGIN
#define FEATURE_OVERRIDE_ENABLE_WEB_POKEDEX_PLUGIN 1
#else
#define FEATURE_OVERRIDE_ENABLE_WEB_POKEDEX_PLUGIN 0
#endif

#ifdef ENABLE_POKEMON_PARTY
#define FEATURE_OVERRIDE_ENABLE_POKEMON_PARTY 1
#else
#define FEATURE_OVERRIDE_ENABLE_POKEMON_PARTY 0
#endif

#ifndef ENABLE_BOOKERLY_FONTS
#define ENABLE_BOOKERLY_FONTS 1
#endif

#ifndef ENABLE_NOTOSANS_FONTS
#define ENABLE_NOTOSANS_FONTS 1
#endif

#ifndef ENABLE_OPENDYSLEXIC_FONTS
#define ENABLE_OPENDYSLEXIC_FONTS 0
#endif

// Legacy alias: ENABLE_EXTENDED_FONTS is true when any extended font family is enabled.
#if ENABLE_BOOKERLY_FONTS || ENABLE_NOTOSANS_FONTS || ENABLE_OPENDYSLEXIC_FONTS
#define ENABLE_EXTENDED_FONTS 1
#else
#define ENABLE_EXTENDED_FONTS 0
#endif

#ifndef ENABLE_IMAGE_SLEEP
#define ENABLE_IMAGE_SLEEP 1
#endif

#ifndef ENABLE_BOOK_IMAGES
#define ENABLE_BOOK_IMAGES 1
#endif

#ifndef ENABLE_MARKDOWN
#define ENABLE_MARKDOWN 1
#endif

#ifndef ENABLE_INTEGRATIONS
#define ENABLE_INTEGRATIONS 0
#endif

#ifndef ENABLE_KOREADER_SYNC
#define ENABLE_KOREADER_SYNC 0
#endif

#ifndef ENABLE_CALIBRE_SYNC
#define ENABLE_CALIBRE_SYNC 0
#endif

#ifndef ENABLE_BACKGROUND_SERVER
#define ENABLE_BACKGROUND_SERVER 1
#endif

#ifndef ENABLE_BACKGROUND_SERVER_ON_CHARGE
#define ENABLE_BACKGROUND_SERVER_ON_CHARGE 0
#endif

#ifndef ENABLE_BACKGROUND_SERVER_ALWAYS
#define ENABLE_BACKGROUND_SERVER_ALWAYS 1
#endif

#ifndef ENABLE_HOME_MEDIA_PICKER
#define ENABLE_HOME_MEDIA_PICKER 1
#endif

#ifndef ENABLE_WEB_POKEDEX_PLUGIN
#define ENABLE_WEB_POKEDEX_PLUGIN 1
#endif

#ifndef ENABLE_POKEMON_PARTY
#define ENABLE_POKEMON_PARTY 1
#endif

#ifndef ENABLE_WEB_WALLPAPER_PLUGIN
#define ENABLE_WEB_WALLPAPER_PLUGIN 0
#endif

#ifndef ENABLE_ANKI_SUPPORT
#define ENABLE_ANKI_SUPPORT 0
#endif

#ifndef ENABLE_TRMNL_SWITCH
#define ENABLE_TRMNL_SWITCH 0
#endif

#ifndef ENABLE_EPUB_SUPPORT
#define ENABLE_EPUB_SUPPORT 1
#endif

#ifndef ENABLE_HYPHENATION
#define ENABLE_HYPHENATION 1
#endif

#ifndef ENABLE_XTC_SUPPORT
#define ENABLE_XTC_SUPPORT 1
#endif

#ifndef ENABLE_LYRA_THEME
#define ENABLE_LYRA_THEME 1
#endif

#ifndef ENABLE_OTA_UPDATES
#define ENABLE_OTA_UPDATES 1
#endif

#ifndef ENABLE_TODO_PLANNER
#define ENABLE_TODO_PLANNER 1
#endif

#ifndef ENABLE_DARK_MODE
#define ENABLE_DARK_MODE 1
#endif

#ifndef ENABLE_VISUAL_COVER_PICKER
#define ENABLE_VISUAL_COVER_PICKER 1
#endif

#ifndef ENABLE_BLE_WIFI_PROVISIONING
#define ENABLE_BLE_WIFI_PROVISIONING 1
#endif

#ifndef ENABLE_USER_FONTS
#define ENABLE_USER_FONTS 1
#endif

#ifndef ENABLE_WEB_WIFI_SETUP
#define ENABLE_WEB_WIFI_SETUP 1
#endif

#ifndef ENABLE_REMOTE_KEYBOARD_INPUT
#define ENABLE_REMOTE_KEYBOARD_INPUT 1
#endif

#ifndef ENABLE_USB_MASS_STORAGE
#define ENABLE_USB_MASS_STORAGE 1
#endif

#ifndef ENABLE_GLOBAL_STATUS_BAR
#define ENABLE_GLOBAL_STATUS_BAR 1
#endif

// Enforce downstream dependencies at compile time.
#if !ENABLE_INTEGRATIONS && FEATURE_OVERRIDE_ENABLE_KOREADER_SYNC && ENABLE_KOREADER_SYNC
#error "ENABLE_KOREADER_SYNC requires ENABLE_INTEGRATIONS=1"
#endif

#if !ENABLE_INTEGRATIONS && FEATURE_OVERRIDE_ENABLE_CALIBRE_SYNC && ENABLE_CALIBRE_SYNC
#error "ENABLE_CALIBRE_SYNC requires ENABLE_INTEGRATIONS=1"
#endif

#if !ENABLE_INTEGRATIONS
#undef ENABLE_KOREADER_SYNC
#define ENABLE_KOREADER_SYNC 0
#undef ENABLE_CALIBRE_SYNC
#define ENABLE_CALIBRE_SYNC 0
#endif

#if !ENABLE_EPUB_SUPPORT && FEATURE_OVERRIDE_ENABLE_HYPHENATION && ENABLE_HYPHENATION
#error "ENABLE_HYPHENATION requires ENABLE_EPUB_SUPPORT=1"
#endif

#if !ENABLE_EPUB_SUPPORT
#undef ENABLE_HYPHENATION
#define ENABLE_HYPHENATION 0
#endif

#if !ENABLE_EPUB_SUPPORT && !ENABLE_MARKDOWN && FEATURE_OVERRIDE_ENABLE_BOOK_IMAGES && ENABLE_BOOK_IMAGES
#error "ENABLE_BOOK_IMAGES requires ENABLE_EPUB_SUPPORT=1 or ENABLE_MARKDOWN=1"
#endif

#if !ENABLE_EPUB_SUPPORT && !ENABLE_MARKDOWN
#undef ENABLE_BOOK_IMAGES
#define ENABLE_BOOK_IMAGES 0
#endif

#if !ENABLE_WEB_POKEDEX_PLUGIN && FEATURE_OVERRIDE_ENABLE_POKEMON_PARTY && ENABLE_POKEMON_PARTY
#error "ENABLE_POKEMON_PARTY requires ENABLE_WEB_POKEDEX_PLUGIN=1"
#endif

#if !ENABLE_WEB_POKEDEX_PLUGIN
#undef ENABLE_POKEMON_PARTY
#define ENABLE_POKEMON_PARTY 0
#endif

#if !ENABLE_BOOKERLY_FONTS && !ENABLE_NOTOSANS_FONTS && FEATURE_OVERRIDE_ENABLE_OPENDYSLEXIC_FONTS && ENABLE_OPENDYSLEXIC_FONTS
#error "ENABLE_OPENDYSLEXIC_FONTS requires ENABLE_BOOKERLY_FONTS=1 or ENABLE_NOTOSANS_FONTS=1"
#endif

#if !ENABLE_BOOKERLY_FONTS && !ENABLE_NOTOSANS_FONTS
#undef ENABLE_OPENDYSLEXIC_FONTS
#define ENABLE_OPENDYSLEXIC_FONTS 0
#endif
